### PR TITLE
TSC-2023-09-07-Meeting-Minutes.md

### PR DESCRIPTION
**Pull request by hdamker**
Agenda proposal for the first TSC meeting on September 7th, 10:00 -11:00 CEST (see https://github.com/camaraproject/Governance#technical-steering-committee for meeting details).

### CODE REVIEW

**Review by bigludo7 — COMMENTED** [review]
Thanks !
Few minor fixes

**Review by bigludo7 — COMMENTED** [review]
One more fixe

**Comment by hdamker** [comment]
> Few minor fixes

Thanks @bigludo7  ... was too late yesterday evening 😉

**Comment by bigludo7** [comment]
@hdamker I've added in this branch the meeting minutes. I did it in a separate file.
Let me know if it works for you to do this way.

As I had to left at the top of the hour I did not follow the discussion on private repo.
do no hesitate to review all points ;)

Thanks

**Comment by hdamker** [comment]
@bigludo7 Thanks a lot for the meeting minutes

> @hdamker I've added in this branch the meeting minutes. I did it in a separate file.
> Let me know if it works for you to do this way.

Yes, that worked for me. See my review changes within https://github.com/camaraproject/Governance/pull/89/commits/65902f07a49fe8bdfc726b17dd1dcc4258d7d335. As the agenda is embedded in the minutes I've deleted the agenda proposal from the PR.

**Comment by hdamker** [comment]
The minutes of the first TSC meeting are open for review by TSC participants until Wednesday, September 14th, 18:00 (CEST).

**Review by bigludo7 — APPROVED** [review]
LGTM

**Pull request merged**
